/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Token } from "./Token";
import { TokenCountArgs } from "./TokenCountArgs";
import { TokenFindManyArgs } from "./TokenFindManyArgs";
import { TokenFindUniqueArgs } from "./TokenFindUniqueArgs";
import { CreateTokenArgs } from "./CreateTokenArgs";
import { UpdateTokenArgs } from "./UpdateTokenArgs";
import { DeleteTokenArgs } from "./DeleteTokenArgs";
import { User } from "../../user/base/User";
import { TokenService } from "../token.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Token)
export class TokenResolverBase {
  constructor(
    protected readonly service: TokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "read",
    possession: "any",
  })
  async _tokensMeta(
    @graphql.Args() args: TokenCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Token])
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "read",
    possession: "any",
  })
  async tokens(@graphql.Args() args: TokenFindManyArgs): Promise<Token[]> {
    return this.service.tokens(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Token, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "read",
    possession: "own",
  })
  async token(
    @graphql.Args() args: TokenFindUniqueArgs
  ): Promise<Token | null> {
    const result = await this.service.token(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Token)
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "create",
    possession: "any",
  })
  async createToken(@graphql.Args() args: CreateTokenArgs): Promise<Token> {
    return await this.service.createToken({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Token)
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "update",
    possession: "any",
  })
  async updateToken(
    @graphql.Args() args: UpdateTokenArgs
  ): Promise<Token | null> {
    try {
      return await this.service.updateToken({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Token)
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "delete",
    possession: "any",
  })
  async deleteToken(
    @graphql.Args() args: DeleteTokenArgs
  ): Promise<Token | null> {
    try {
      return await this.service.deleteToken(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Token): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
